server:
  port: 18082
spring:
  application:
    name: seckill-search
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        #Nacos的注册地址
        server-addr: 127.0.0.1:8848
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.220.128:9300
#超时配置
ribbon:
  ReadTimeout: 3000000
logging:
  pattern:
    console: "%msg%n"